# ===============================
# Configuración del Servidor
# ===============================
spring.application.name=LearnTrack
server.port=8080

# ===============================
# Conexión a PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:learntrack_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# ===============================
# Configuración de Hibernate / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Configuración de Mail
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=copitocorp.soporte@gmail.com
spring.mail.password=uglw qpni narq hhya
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# Configuración de Ollama
# ===============================
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi3:mini

# ===============================
# Configuración de JWT
# ===============================
jwt.secret=${JWT_SECRET:TuClaveSecretaSuperSeguraParaLearnTrackQueDebeSerLargaChangeInProduction}
jwt.expiration=86400000